
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_core_gold_employee_workforce'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'mdona'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  DBT_NODEV_ENVS: ['pro','pre','itg']
  FORCE_CONTRACT_ENVS: []

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

models:
  dbt_core_gold_employee_workforce:
    # Config indicated by + and applies to all files under models/example/

############### MARTS ###############
    marts:
      +database: "bq-mercadona" # cambiarlo en un futuro por "mdona-data-{{target.name}}-gold"
      +materialized: table
      +docs:
        node_color: gold
      
      employee_workforce:
        +schema: "store_workforce" #revisar si se quiere este nombre
        +tags:
          - "employeeworkforce" #revisar si se quiere este nombre
          - "gold"
        +labels:
          layer: gold
          cu: workforce

  ############### STAGING ###############        
    staging:
      +database: "bq-mercadona" # cambiarlo en un futuro por "mdona-data-{{target.name}}-gold"
      +materialized: table
      +docs:
        node_color: silver

      employee_workforce:
        +schema: "stg_store_workforce"
        +materialized: table
        +tags:
          - "employeeworkforce" #revisar si se quiere este nombre
          - "silver"
        +labels:
          layer: silver
          cu: workforce